/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 burger.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/burger.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.bottom_bread_0.geometry} material={materials.bread} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tomato_tomato_0.geometry} material={materials.tomato} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.salat001_salat_0.geometry} material={materials.salat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.salat_salat_0.geometry} material={materials.salat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.salat002_salat_0.geometry} material={materials.salat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.cheese_cheese_0.geometry} material={materials.cheese} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.cheese001_cheese_0.geometry} material={materials.cheese} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.meat_meat_0.geometry} material={materials.meat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.top_bread001_0.geometry} material={materials['bread.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.meat001_meat_0.geometry} material={materials.meat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/burger.glb')
