/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mouse.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function MouseGLB(props) {
  const { nodes, materials } = useGLTF('/models/little-mouse/mouse.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh geometry={nodes.Voxelize_a1_principledshader1_0.geometry} material={materials.principledshader1} />
        <mesh geometry={nodes.Voxelize_a1_principledshader1_0_1.geometry} material={materials.principledshader1} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse.glb')
