/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx shark.glb
EScribir export default function para evitarpagina en blanco
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function SharkGLB(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/shark.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Shark_Armature_44" position={[-0.038, 0, 0]} rotation={[-1.584, -Math.PI / 2, 0]} scale={1.766}>
                <group name="GLTF_created_0">
                  <group name="BT_Shark__0_42" />
                  <group name="BT_Shark__1_43" />
                  <group name="Shark_Armature_rootJoint_41" position={[-12.35, 0.174, -0.415]} rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Master_Bone_Shark_Armature_40" rotation={[1.608, 0, -Math.PI / 2]}>
                      <group name="CTRL_L_Body_Shark_Armature_0" position={[0, 1.611, 0.708]} rotation={[-3.127, 0.083, -Math.PI]} />
                      <group name="CTRL_Tail_Shark_Armature_1" position={[0.007, 1.613, -0.424]} rotation={[-3.127, -0.136, -Math.PI]} />
                      <primitive object={nodes.Body_Shark_Armature_4} />
                      <group name="CTRL_Secondary'_Shark_Armature_5" position={[0, 1.613, -1.45]} rotation={[-3.127, -0.34, -Math.PI]} scale={[1, 1.001, 1]} />
                      <group name="CTRL_Tail_End_Shark_Armature_6" position={[-0.007, 1.812, -1.42]} rotation={[-3.127, -0.885, Math.PI]} scale={[1, 1.001, 1]} />
                      <group name="CTRL_L_Body001_Shark_Armature_7" position={[0, 1.612, 0.098]} rotation={[-3.127, 0.056, -Math.PI]} scale={[1, 0.998, 1]} />
                      <primitive object={nodes.Body001_Shark_Armature_33} />
                      <primitive object={nodes.Body002_Shark_Armature_35} />
                      <primitive object={nodes.Body003_Shark_Armature_37} />
                      <group name="CTRL_Head_Shark_Armature_38" position={[0, 1.618, 2.041]} rotation={[0.014, 0.035, 0]} />
                      <group name="CTRL_Mid_Shark_Armature_39" position={[0, 1.611, 1.641]} rotation={[-3.127, -0.06, -Math.PI]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Diffuse} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Diffuse_Eye} skeleton={nodes.Object_8.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shark.glb')
